### ISSUE TITLE
Submodule react-devtools error

### ISSUE THREAD

**Issue by xlarsx** [bruderstein/react-render-hook#2]
Hi good day,
Since today when we update our dependencies we found some errors when testing the system:

```
 TypeError: Cannot read property 'displayName' of undefined
```

And it seems that is because some validation that is missing in the react-devtools, we just post [the pull request](https://github.com/facebook/react-devtools/pull/360) but meanwhile is accepted the system is failing... could you please help us to revert the git submodule?

Thanks for your support! Greetings,

**Comment by bruderstein** [comment]
How are you creating an `undefined` component?  That shouldn't really be possible...  It's more likely there's an issue in this project, or somewhere in the unexpected-react stack that causes this.

**Comment by diazod** [comment]
@bruderstein for what I have investigated this is the commit causing the issue

https://github.com/facebook/react-devtools/commit/7efca36b6ba2801233168a02c3cb32032d10e424

**Comment by bruderstein** [comment]
That is exactly the commit we need in order to see rendered `0`  (take a look at a react component that renders `<div>Hello {0}</div>` - you'll see `<div>Hello </></div>` in the devtools, and it breaks unexpected-react.

I still don't understand how you're arriving at the issue you're getting. Would it be possible to create a mini-repro?  Or describe at least how you are creating  (or what you mean by) an "undefined" component.

**Comment by diazod** [comment]
@bruderstein We found the issue; apparently we were trying to render an empty string value which in old version was a falsy value.
Sorry for the inconvinience

**Comment by xlarsx** [comment]
Thank you very much.

Greetings,
